console.log("Hey Prasanna!!!!!");
age = 20;
Name = "Prasanna Kundurthi";
console.log("My name is " + Name + " and I am " + age + "years old");
x = null;
console.log(x);
console.log(typeof x);
y = undefined;
console.log(y);
console.log(typeof y);
isFollow = true;
console.log(isFollow);
console.log(typeof isFollow);
let age1 = 20;
let degree = "B.Tech";
console.log(age1);
var age2 = 18;
var age2 = 21;
var age2 = 22;
console.log(age2);
const age3 = 24;
age3 = 26;
age3 = 29;
console.log(age3);
let a;
console.log(a);
console.log(typeof a);